image_size: 32
patch_size: 2
num_classes: 10
num_epochs: 10
batch_size: 128
learning_rate: 0.001
n_embd: 768
dim_att: 768 # dim_att = n_embd
dim_ffn: 3072 # n_embd * 4
n_layer: 6
betas: (0.9, 0.999)
adam_eps: 1e-8
