dataset: cifar10
image_size: 32
patch_size: 16
num_classes: 10
num_epochs: 400
batch_size: 2048
learning_rate: 0.001
n_embd: 768
dim_att: 768 # dim_att = n_embd
dim_ffn: 3072 # n_embd * 4
n_layer: 6
beta_1: 0.9
beta_2: 0.999
adam_eps: 1e-8
weight_decay: 0.01
dropout: 0.0
print_step: 25
