image_size: 32
patch_size: 2
num_classes: 10
num_epochs: 10
batch_size: 256
learning_rate: 0.1
n_embd: 64
dim_att: 64 # dim_att = n_embd
dim_ffn: 256 # n_embd * 4
n_layer: 6
beta_1: 0.9
beta_2: 0.999
adam_eps: 1e-8
weight_decay: 5e-4
