dataset: imagenet1k
resume: 1
ckpt_path: '/home/sort/ved/ViR/ckpt/'
image_size: 224
patch_size: 16
max_norm: 1
num_classes: 1000
num_epochs: 400
eval_epoch: 5
batch_size: 224
dconv: 1
learning_rate: 0.0001
n_embd: 768
dim_att: 768 # dim_att = n_embd
dim_ffn: 3072 # n_embd * 4
n_layer: 12
num_heads: 12
beta_1: 0.9
beta_2: 0.999
adam_eps: 1e-12
opt: 'adam'
weight_decay: 0.0001
zo_eps: 0.001
dropout: 0.0
print_step: 100

